USE aigc;

-- 检查表结构
DESCRIBE users;

-- 添加缺失的字段
ALTER TABLE users ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 再次检查表结构确认修改成功
DESCRIBE users;